// AUTO-GENERATED by ERTK codegen. Do not edit.
import expandTaskSuggestionEndpoint from "@pointwise/endpoints/llm/task-expand";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const POST = createRouteHandler(expandTaskSuggestionEndpoint);
