// AUTO-GENERATED by ERTK codegen. Do not edit.
import rejectJoinRequestEndpoint from "@pointwise/endpoints/projects/[id]/join-requests/[targetId]/reject";
import { createRouteHandler } from "@pointwise/lib/ertk/route-handler";

export const DELETE = createRouteHandler(rejectJoinRequestEndpoint);
