// AUTO-GENERATED by ERTK codegen. Do not edit.
import updateTaskAssignmentsEndpoint from "@pointwise/endpoints/tasks/[id]/assign";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const PATCH = createRouteHandler(updateTaskAssignmentsEndpoint);
