// AUTO-GENERATED by ERTK codegen. Do not edit.
import searchPublicProjectsEndpoint from "@pointwise/endpoints/projects/public";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const GET = createRouteHandler(searchPublicProjectsEndpoint);
