// AUTO-GENERATED by ERTK codegen. Do not edit.
import deletePostEndpoint from "@pointwise/endpoints/users/[id]/posts/[postId]/delete";
import editPostEndpoint from "@pointwise/endpoints/users/[id]/posts/[postId]/update";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const DELETE = createRouteHandler(deletePostEndpoint);
export const PATCH = createRouteHandler(editPostEndpoint);
