// AUTO-GENERATED by ERTK codegen. Do not edit.
import createCommentEndpoint from "@pointwise/endpoints/tasks/[id]/comments/create";
import getCommentsEndpoint from "@pointwise/endpoints/tasks/[id]/comments/list";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const POST = createRouteHandler(createCommentEndpoint);
export const GET = createRouteHandler(getCommentsEndpoint);
