// AUTO-GENERATED by ERTK codegen. Do not edit.
import getFriendshipStatusEndpoint from "@pointwise/endpoints/friends/[id]/status";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const GET = createRouteHandler(getFriendshipStatusEndpoint);
