// AUTO-GENERATED by ERTK codegen. Do not edit.
import getUserProfileEndpoint from "@pointwise/endpoints/users/[id]/profile";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const GET = createRouteHandler(getUserProfileEndpoint);
