// AUTO-GENERATED by ERTK codegen. Do not edit.
import updateCreditSettingsEndpoint from "@pointwise/endpoints/projects/[id]/credit-settings";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const PATCH = createRouteHandler(updateCreditSettingsEndpoint);
