// AUTO-GENERATED by ERTK codegen. Do not edit.
import likePostCommentEndpoint from "@pointwise/endpoints/users/[id]/posts/[postId]/comments/[commentId]/like";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const POST = createRouteHandler(likePostCommentEndpoint);
