// AUTO-GENERATED by ERTK codegen. Do not edit.
import cancelRequestToJoinProjectEndpoint from "@pointwise/endpoints/projects/[id]/cancel-join-request";
import { createRouteHandler } from "@pointwise/lib/ertk/route-handler";

export const DELETE = createRouteHandler(cancelRequestToJoinProjectEndpoint);
