// AUTO-GENERATED by ERTK codegen. Do not edit.
import getAccountInfoEndpoint from "@pointwise/endpoints/user/account-info";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const GET = createRouteHandler(getAccountInfoEndpoint);
