// AUTO-GENERATED by ERTK codegen. Do not edit.
import createConversationEndpoint from "@pointwise/endpoints/conversations/create";
import getConversationsEndpoint from "@pointwise/endpoints/conversations/list";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const POST = createRouteHandler(createConversationEndpoint);
export const GET = createRouteHandler(getConversationsEndpoint);
