// AUTO-GENERATED by ERTK codegen. Do not edit.
import revokeAllDeviceSessionsEndpoint from "@pointwise/endpoints/user/device-sessions/revoke-all";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const POST = createRouteHandler(revokeAllDeviceSessionsEndpoint);
