// AUTO-GENERATED by ERTK codegen. Do not edit.
import likePostEndpoint from "@pointwise/endpoints/users/[id]/posts/[postId]/like";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const POST = createRouteHandler(likePostEndpoint);
