// AUTO-GENERATED by ERTK codegen. Do not edit.
import createPostReplyEndpoint from "@pointwise/endpoints/users/[id]/posts/[postId]/comments/[commentId]/replies/create";
import getPostRepliesEndpoint from "@pointwise/endpoints/users/[id]/posts/[postId]/comments/[commentId]/replies/list";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const POST = createRouteHandler(createPostReplyEndpoint);
export const GET = createRouteHandler(getPostRepliesEndpoint);
