// AUTO-GENERATED by ERTK codegen. Do not edit.
import getXPEndpoint from "@pointwise/endpoints/user/xp/get";
import updateXPEndpoint from "@pointwise/endpoints/user/xp/update";
import { createRouteHandler } from "@pointwise/lib/ertk/route-handler";

export const GET = createRouteHandler(getXPEndpoint);
export const PATCH = createRouteHandler(updateXPEndpoint);
