// AUTO-GENERATED by ERTK codegen. Do not edit.
import requestToJoinProjectEndpoint from "@pointwise/endpoints/projects/[id]/join-request";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const POST = createRouteHandler(requestToJoinProjectEndpoint);
