// AUTO-GENERATED by ERTK codegen. Do not edit.
import getProjectJoinRequestsEndpoint from "@pointwise/endpoints/projects/[id]/join-requests/list";
import { createRouteHandler } from "@pointwise/lib/ertk/route-handler";

export const GET = createRouteHandler(getProjectJoinRequestsEndpoint);
