// AUTO-GENERATED by ERTK codegen. Do not edit.
import getCreditBalanceEndpoint from "@pointwise/endpoints/credits/balance";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const GET = createRouteHandler(getCreditBalanceEndpoint);
