// AUTO-GENERATED by ERTK codegen. Do not edit.
import leaveConversationEndpoint from "@pointwise/endpoints/conversations/[id]/leave";
import { createRouteHandler } from "@pointwise/lib/ertk/route-handler";

export const DELETE = createRouteHandler(leaveConversationEndpoint);
