// AUTO-GENERATED by ERTK codegen. Do not edit.
import getProjectMembersEndpoint from "@pointwise/endpoints/projects/[id]/members";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const GET = createRouteHandler(getProjectMembersEndpoint);
