// AUTO-GENERATED by ERTK codegen. Do not edit.
import updateMemberRoleEndpoint from "@pointwise/endpoints/projects/[id]/members/[targetId]/update-role";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const PATCH = createRouteHandler(updateMemberRoleEndpoint);
