// AUTO-GENERATED by ERTK codegen. Do not edit.
import cancelFriendRequestEndpoint from "@pointwise/endpoints/friends/requests/[id]/cancel";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const DELETE = createRouteHandler(cancelFriendRequestEndpoint);
