// AUTO-GENERATED by ERTK codegen. Do not edit.
import removeProjectMemberEndpoint from "@pointwise/endpoints/projects/[id]/members/[targetId]/remove";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const DELETE = createRouteHandler(removeProjectMemberEndpoint);
