// AUTO-GENERATED by ERTK codegen. Do not edit.
import getFriendsEndpoint from "@pointwise/endpoints/friends/list";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const GET = createRouteHandler(getFriendsEndpoint);
