// AUTO-GENERATED by ERTK codegen. Do not edit.
import canInviteEndpoint from "@pointwise/endpoints/projects/[id]/can-invite";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const GET = createRouteHandler(canInviteEndpoint);
