// AUTO-GENERATED by ERTK codegen. Do not edit.
import deleteCommentEndpoint from "@pointwise/endpoints/tasks/[id]/comments/[commentId]/delete";
import editCommentEndpoint from "@pointwise/endpoints/tasks/[id]/comments/[commentId]/update";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const DELETE = createRouteHandler(deleteCommentEndpoint);
export const PATCH = createRouteHandler(editCommentEndpoint);
