// AUTO-GENERATED by ERTK codegen. Do not edit.
import createProjectEndpoint from "@pointwise/endpoints/projects/create";
import getProjectsEndpoint from "@pointwise/endpoints/projects/list";
import { createRouteHandler } from "@pointwise/lib/ertk/route-handler";

export const POST = createRouteHandler(createProjectEndpoint);
export const GET = createRouteHandler(getProjectsEndpoint);
