// AUTO-GENERATED by ERTK codegen. Do not edit.
import getNotificationSettingsEndpoint from "@pointwise/endpoints/user/notification-settings/get";
import updateNotificationSettingsEndpoint from "@pointwise/endpoints/user/notification-settings/update";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const GET = createRouteHandler(getNotificationSettingsEndpoint);
export const PATCH = createRouteHandler(updateNotificationSettingsEndpoint);
