// AUTO-GENERATED by ERTK codegen. Do not edit.
import createTaskEndpoint from "@pointwise/endpoints/tasks/create";
import getTasksEndpoint from "@pointwise/endpoints/tasks/get";
import { createRouteHandler } from "@pointwise/lib/ertk/route-handler";

export const POST = createRouteHandler(createTaskEndpoint);
export const GET = createRouteHandler(getTasksEndpoint);
