// AUTO-GENERATED by ERTK codegen. Do not edit.
import dismissNotificationsEndpoint from "@pointwise/endpoints/notifications/dismiss";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const PATCH = createRouteHandler(dismissNotificationsEndpoint);
