// AUTO-GENERATED by ERTK codegen. Do not edit.
import unlikeTaskEndpoint from "@pointwise/endpoints/tasks/[id]/unlike";
import { createRouteHandler } from "@pointwise/lib/ertk/route-handler";

export const DELETE = createRouteHandler(unlikeTaskEndpoint);
