// AUTO-GENERATED by ERTK codegen. Do not edit.
import inviteUsersToProjectEndpoint from "@pointwise/endpoints/projects/[id]/invite";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const POST = createRouteHandler(inviteUsersToProjectEndpoint);
