// AUTO-GENERATED by ERTK codegen. Do not edit.
import transferOwnershipEndpoint from "@pointwise/endpoints/projects/[id]/transfer-ownership";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const POST = createRouteHandler(transferOwnershipEndpoint);
