// AUTO-GENERATED by ERTK codegen. Do not edit.
import searchUsersEndpoint from "@pointwise/endpoints/users/search";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const GET = createRouteHandler(searchUsersEndpoint);
