// AUTO-GENERATED by ERTK codegen. Do not edit.
import getTaskBreakdownEndpoint from "@pointwise/endpoints/llm/task-breakdown";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const POST = createRouteHandler(getTaskBreakdownEndpoint);
