// AUTO-GENERATED by ERTK codegen. Do not edit.
import likeCommentEndpoint from "@pointwise/endpoints/tasks/[id]/comments/[commentId]/like";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const POST = createRouteHandler(likeCommentEndpoint);
