// AUTO-GENERATED by ERTK codegen. Do not edit.
import getUserEndpoint from "@pointwise/endpoints/user/get";
import updateUserEndpoint from "@pointwise/endpoints/user/update";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const GET = createRouteHandler(getUserEndpoint);
export const PATCH = createRouteHandler(updateUserEndpoint);
