// AUTO-GENERATED by ERTK codegen. Do not edit.
import deleteReadNotificationsEndpoint from "@pointwise/endpoints/notifications/delete-read";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const DELETE = createRouteHandler(deleteReadNotificationsEndpoint);
