// AUTO-GENERATED by ERTK codegen. Do not edit.
import rejectInviteEndpoint from "@pointwise/endpoints/invites/[id]/reject";
import { createRouteHandler } from "@pointwise/lib/ertk/route-handler";

export const DELETE = createRouteHandler(rejectInviteEndpoint);
