// AUTO-GENERATED by ERTK codegen. Do not edit.
import getTaskSuggestionsEndpoint from "@pointwise/endpoints/llm/task-suggestions";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const POST = createRouteHandler(getTaskSuggestionsEndpoint);
