// AUTO-GENERATED by ERTK codegen. Do not edit.
import unlikePostEndpoint from "@pointwise/endpoints/users/[id]/posts/[postId]/unlike";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const DELETE = createRouteHandler(unlikePostEndpoint);
