// AUTO-GENERATED by ERTK codegen. Do not edit.
import unlikeCommentEndpoint from "@pointwise/endpoints/tasks/[id]/comments/[commentId]/unlike";
import { createRouteHandler } from "@pointwise/lib/ertk/route-handler";

export const DELETE = createRouteHandler(unlikeCommentEndpoint);
