// AUTO-GENERATED by ERTK codegen. Do not edit.
import checkDisplayNameAvailabilityEndpoint from "@pointwise/endpoints/user/check-availability";
import { createRouteHandler } from "@pointwise/lib/ertk/route-handler";

export const GET = createRouteHandler(checkDisplayNameAvailabilityEndpoint);
