// AUTO-GENERATED by ERTK codegen. Do not edit.
import getProjectAnalyticsEndpoint from "@pointwise/endpoints/projects/[id]/analytics";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const GET = createRouteHandler(getProjectAnalyticsEndpoint);
