// AUTO-GENERATED by ERTK codegen. Do not edit.
import getPendingRequestsEndpoint from "@pointwise/endpoints/friends/requests/list";
import sendFriendRequestEndpoint from "@pointwise/endpoints/friends/requests/send";
import { createRouteHandler } from "@pointwise/lib/ertk/route-handler";

export const GET = createRouteHandler(getPendingRequestsEndpoint);
export const POST = createRouteHandler(sendFriendRequestEndpoint);
