// AUTO-GENERATED by ERTK codegen. Do not edit.
import getDeviceSessionsEndpoint from "@pointwise/endpoints/user/device-sessions/list";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const GET = createRouteHandler(getDeviceSessionsEndpoint);
