// AUTO-GENERATED by ERTK codegen. Do not edit.
import removeFriendEndpoint from "@pointwise/endpoints/friends/[id]/remove";
import { createRouteHandler } from "@pointwise/lib/ertk/route-handler";

export const DELETE = createRouteHandler(removeFriendEndpoint);
