// AUTO-GENERATED by ERTK codegen. Do not edit.
import createPostCommentEndpoint from "@pointwise/endpoints/users/[id]/posts/[postId]/comments/create";
import getPostCommentsEndpoint from "@pointwise/endpoints/users/[id]/posts/[postId]/comments/list";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const POST = createRouteHandler(createPostCommentEndpoint);
export const GET = createRouteHandler(getPostCommentsEndpoint);
