// AUTO-GENERATED by ERTK codegen. Do not edit.
import archiveConversationEndpoint from "@pointwise/endpoints/conversations/[id]/archive";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const PATCH = createRouteHandler(archiveConversationEndpoint);
