// AUTO-GENERATED by ERTK codegen. Do not edit.
import getProjectCreditUsageEndpoint from "@pointwise/endpoints/projects/[id]/credit-usage";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const GET = createRouteHandler(getProjectCreditUsageEndpoint);
