// AUTO-GENERATED by ERTK codegen. Do not edit.
import acceptInviteEndpoint from "@pointwise/endpoints/invites/[id]/accept";
import { createRouteHandler } from "@pointwise/lib/ertk/route-handler";

export const POST = createRouteHandler(acceptInviteEndpoint);
