// AUTO-GENERATED by ERTK codegen. Do not edit.
import getDeletePreviewEndpoint from "@pointwise/endpoints/user/delete-preview";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const GET = createRouteHandler(getDeletePreviewEndpoint);
