// AUTO-GENERATED by ERTK codegen. Do not edit.
import leaveProjectEndpoint from "@pointwise/endpoints/projects/[id]/leave";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const DELETE = createRouteHandler(leaveProjectEndpoint);
