// AUTO-GENERATED by ERTK codegen. Do not edit.
import handleFriendRequestEndpoint from "@pointwise/endpoints/friends/requests/[id]/handle";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const PATCH = createRouteHandler(handleFriendRequestEndpoint);
