// AUTO-GENERATED by ERTK codegen. Do not edit.
import getNotificationsEndpoint from "@pointwise/endpoints/notifications/list";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const GET = createRouteHandler(getNotificationsEndpoint);
