// AUTO-GENERATED by ERTK codegen. Do not edit.
import deletePostCommentEndpoint from "@pointwise/endpoints/users/[id]/posts/[postId]/comments/[commentId]/delete";
import editPostCommentEndpoint from "@pointwise/endpoints/users/[id]/posts/[postId]/comments/[commentId]/update";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const DELETE = createRouteHandler(deletePostCommentEndpoint);
export const PATCH = createRouteHandler(editPostCommentEndpoint);
