// AUTO-GENERATED by ERTK codegen. Do not edit.
import getXpSuggestionEndpoint from "@pointwise/endpoints/llm/xp-suggestion";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const POST = createRouteHandler(getXpSuggestionEndpoint);
