// AUTO-GENERATED by ERTK codegen. Do not edit.
import getMessagesEndpoint from "@pointwise/endpoints/conversations/[id]/messages/list";
import sendMessageEndpoint from "@pointwise/endpoints/conversations/[id]/messages/send";
import { createRouteHandler } from "@pointwise/lib/ertk/route-handler";

export const GET = createRouteHandler(getMessagesEndpoint);
export const POST = createRouteHandler(sendMessageEndpoint);
