// AUTO-GENERATED by ERTK codegen. Do not edit.
import likeTaskEndpoint from "@pointwise/endpoints/tasks/[id]/like";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const POST = createRouteHandler(likeTaskEndpoint);
