// AUTO-GENERATED by ERTK codegen. Do not edit.
import approveJoinRequestEndpoint from "@pointwise/endpoints/projects/[id]/join-requests/[targetId]/approve";
import { createRouteHandler } from "@pointwise/lib/ertk/route-handler";

export const PATCH = createRouteHandler(approveJoinRequestEndpoint);
