// AUTO-GENERATED by ERTK codegen. Do not edit.
import createPostEndpoint from "@pointwise/endpoints/users/[id]/posts/create";
import getUserPostsEndpoint from "@pointwise/endpoints/users/[id]/posts/list";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const POST = createRouteHandler(createPostEndpoint);
export const GET = createRouteHandler(getUserPostsEndpoint);
