// AUTO-GENERATED by ERTK codegen. Do not edit.
import getProjectInvitesEndpoint from "@pointwise/endpoints/projects/[id]/invites";
import { createRouteHandler } from "@pointwise/lib/ertk/route-handler";

export const GET = createRouteHandler(getProjectInvitesEndpoint);
