// AUTO-GENERATED by ERTK codegen. Do not edit.
import getConversationEndpoint from "@pointwise/endpoints/conversations/[id]/get";
import updateConversationEndpoint from "@pointwise/endpoints/conversations/[id]/update";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const GET = createRouteHandler(getConversationEndpoint);
export const PATCH = createRouteHandler(updateConversationEndpoint);
