// AUTO-GENERATED by ERTK codegen. Do not edit.
import getReceivedInvitesEndpoint from "@pointwise/endpoints/invites/list";
import { createRouteHandler } from "@pointwise/lib/ertk/route-handler";

export const GET = createRouteHandler(getReceivedInvitesEndpoint);
