// AUTO-GENERATED by ERTK codegen. Do not edit.
import deleteNotificationEndpoint from "@pointwise/endpoints/notifications/[id]/delete";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const DELETE = createRouteHandler(deleteNotificationEndpoint);
