// AUTO-GENERATED by ERTK codegen. Do not edit.
import markAllReadEndpoint from "@pointwise/endpoints/notifications/mark-all-read";
import { createRouteHandler } from "@pointwise/lib/ertk/route-handler";

export const PATCH = createRouteHandler(markAllReadEndpoint);
