// AUTO-GENERATED by ERTK codegen. Do not edit.
import unlikePostCommentEndpoint from "@pointwise/endpoints/users/[id]/posts/[postId]/comments/[commentId]/unlike";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const DELETE = createRouteHandler(unlikePostCommentEndpoint);
