// AUTO-GENERATED by ERTK codegen. Do not edit.
import markConversationReadEndpoint from "@pointwise/endpoints/conversations/[id]/read";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const PATCH = createRouteHandler(markConversationReadEndpoint);
