// AUTO-GENERATED by ERTK codegen. Do not edit.
import createReplyEndpoint from "@pointwise/endpoints/tasks/[id]/comments/[commentId]/replies/create";
import getRepliesEndpoint from "@pointwise/endpoints/tasks/[id]/comments/[commentId]/replies/list";
import { createRouteHandler } from "@pointwise/lib/ertk-handler";

export const POST = createRouteHandler(createReplyEndpoint);
export const GET = createRouteHandler(getRepliesEndpoint);
